apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-app
  labels:
    app: multi-container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
        - name: hotel-service
          image: quay.io/skoshchi/hotel-service:latest
          ports:
            - containerPort: 8081
        - name: order-status
          image: quay.io/skoshchi/sidecar:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: multi-container-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar
spec:
  selector:
    app: multi-container-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
#apiVersion: route.openshift.io/v1
#kind: Route
#metadata:
#  name: hotel-service-route
#spec:
#  to:
#    kind: Service
#    name: hotel-service
#  port:
#    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sidecar
spec:
  to:
    kind: Service
    name: sidecar
  port:
    targetPort: 8081
