apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  labels:
    app: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: quay.io/skoshchi/hotel-service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hotel-service
spec:
  to:
    kind: Service
    name: hotel-service
  port:
    targetPort: 8082
